name: Build & Release Package

on:
  push:
    branches:
      - master
      - bug/NT24-24-router-issue
  release:
    types:
      - released

permissions:
  id-token: write
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Validate composer.json and composer.lock
        working-directory: libraries/tour-manager
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install PHP dependencies
        working-directory: libraries/tour-manager
        run: composer install --prefer-dist --no-progress

      - name: "Package Library: Tour Manager"
        working-directory: libraries/tour-manager
        run: zip -qq -r ../../lib_tour-manager.zip .

      - name: "Package Plugin: GeoIP"
        working-directory: plugins/system/rezkit_geoip
        run: zip -qq -r ../../../plg_system_rezkit_geoip.zip .

      - name: "Package Plugin: RK Tours"
        working-directory: plugins/system/rktours
        run: zip -qq -r ../../../plg_system_rktours.zip .

      - name: "Package Plugin: Tour Search"
        working-directory: plugins/system/toursearch
        run: zip -qq -r ../../../plg_system_toursearch.zip .

      - name: "Package Component: RK Tours"
        working-directory: components/com_rktours
        run: zip -qq -r ../../com_rktours.zip .

      - name: "Package Plugin: Tour Site Map"
        working-directory: plugins/system/tours_sitemap
        run: zip -qq -r ../../../plg_osmap_tours_sitemap.zip .

      - name: "Generate package payload"
        run: >
            zip -qq 
            tour-manager.zip
            package.xml
            com_rktours.zip
            lib_tour-manager.zip
            plg_system_rktours.zip
            plg_system_rezkit_geoip.zip
            plg_system_toursearch.zip
            plg_osmap_tours_sitemap.zip

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tour-manager.zip
          path: tour-manager.zip

  upload:
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: tour-manager.zip

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: GitHubActionRun-${{github.run_number}}
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::205331266135:role/gha.uploadJoomlaPackages

      - name: Generate update/package file
        run: |
          sed -i -e 's/__VERSION__/${{github.run_number}}/g' update.xml
          sed -i -e 's/__VERSION__/${{github.run_number}}/g' package.xml

      - name: Upload package
        run: |
          aws s3 cp ./tour-manager.zip s3://updates.mrzen.com/j4/tour-manager/tour-manager-${{github.run_number}}.zip
          aws s3 cp ./tour-manager.zip s3://updates.mrzen.com/j4/tour-manager/tour-manager-latest.zip
          aws s3 cp ./update.xml s3://updates.mrzen.com/j4/tour-manager/update.xml
