name: Build & Release Package

on:
  push:
    branches:
      - master
  release:
    types:
      - released

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Validate composer.json and composer.lock
        working-directory: libraries/tour-manager
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3.3.2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install PHP dependencies
        working-directory: libraries/tour-manager
        run: composer install --prefer-dist --no-progress

      - name: "Package Library: Tour Manager"
        working-directory: libraries/tour-manager
        run: zip -qq -r ../../lib_tour-manager.zip .

      - name: "Package Plugin: Tour Manager Sync"
        working-directory: plugins/system/tour_manager_sync
        run: zip -qq -r ../../../plg_system_tour_manager_sync.zip .

      - name: "Package Plugin: GeoIP"
        working-directory: plugins/system/rezkit_geoip
        run: zip -qq -r ../../../plg_system_rezkit_geoip.zip .

      - name: "Package Plugin: Tour Search"
        working-directory: plugins/system/toursearch
        run: zip -qq -r ../../../plg_system_toursearch.zip .

      - name: "Package Plugin: Tour Site Map"
        working-directory: plugins/system/tours_sitemap
        run: zip -qq -r ../../../plg_system_tours_sitemap.zip .

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tour-manager
          path: |
            package.xml
            lib_tour-manager.zip
            plg_system_tour_manager_sync.zip
            plg_system_rezkit_geoip.zip
            plg_system_toursearch.zip
            plg_system_tours_sitemap.zip

  upload_to_repo:
    name: Upload to S3
    runs-on: ubuntu-22.04
    needs: [build]
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::205331266135:role/github-actions-tour-manager-joomla4-build-upload
          role-session-name: github-action-run
          aws-region: eu-west-1
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: tour-manager
      - name: Upload to S3 as 'latest'
        run: aws s3 cp tour-manager "s3://updates.mrzen.com/j4/tour-manager/latest.zip"        
