name: Build & Release Package

on:
  push:
    branches:
      - master
  release:
    types:
      - released

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Validate composer.json and composer.lock
        working-directory: libraries/tour-manager
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install PHP dependencies
        working-directory: libraries/tour-manager
        run: composer install --prefer-dist --no-progress

      - name: "Package Library: Tour Manager"
        working-directory: libraries/tour-manager
        run: zip -qq -r ../../lib_tour-manager.zip .

      - name: "Package Plugin: Tour Manager Sync"
        working-directory: plugins/system/tour_manager_sync
        run: zip -qq -r ../../../plg_system_tour_manager_sync.zip .

      - name: "Package Plugin: GeoIP"
        working-directory: plugins/system/rezkit_geoip
        run: zip -qq -r ../../../plg_system_rezkit_geoip.zip .

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tour-manager
          path: |
            package.xml
            lib_tour-manager.zip
            plg_system_tour_manager_sync.zip
            plg_system_rezkit_geoip.zip
